### ISSUE TITLE
Add support for WooCommerce HPOS

### ISSUE THREAD

**Issue by helgatheviking** [wpcodefactory/admin-bar-addition-for-woocommerce#1]
With plugin active, go to WooCommerce > Settings > Advanced > Features. Under “Experimental Features” there’s an option for “High-Performance order storage (COT)” but it’s grayed out and cites this plugin:

>This feature shouldn’t be enabled, the Admin Bar Addition for WooCommerce plugin is active and isn’t compatible with it. Manage incompatible plugins

Assuming this plugin isn’t interacting with Orders much, the only thing I can think that needs updating would be the link in the toolbar nodes to the orders

[source](https://wordpress.org/support/topic/add-support-for-woocommerce-hpos/)

**Comment by algoritmika** [comment]
Fixed in the plugin v1.3.0.
